In [137]:
import pandas as pd
import numpy as np

data = pd.read_table('sample_data/input_11.txt',header = None)

In [138]:
def time_step():
  for i in range(m):
    for j in range(n):
      mat_dat[i,j] =  mat_dat[i,j] + 1

def flash(x,y):
  neighbors = []
  has_flashed[x][y] = 1
  mat_dat[x,y] = 0
  if x > 0:
    neighbors.append([x-1,y])
    if y > 0:
      neighbors.append([x-1,y-1])
      neighbors.append([x,y-1])
    if y < (m-1):
      neighbors.append([x-1,y+1])
      neighbors.append([x,y+1])
  if x < (n-1):
    neighbors.append([x+1,y])
    if y > 0:
      neighbors.append([x+1,y-1])
      neighbors.append([x,y-1])
    if y < (m-1):
      neighbors.append([x+1,y+1])
      neighbors.append([x,y+1])
  neighbors_res = []
  for p in neighbors:
    if p not in neighbors_res:
      neighbors_res.append(p)
      if has_flashed[p[0]][p[1]]== 0:
        mat_dat[p[0],p[1]] = mat_dat[p[0],p[1]] + 1



  


In [139]:
data_int = []
n = data.shape[0]
for i in range(n):
  data_int.append([int(x) for x in str(data[0][i])])

mat_dat = np.array(data_int)
m = mat_dat.shape[1]

In [140]:
total = 0
tt = 100
for t in range(tt):
  time_step()
  has_flashed = np.zeros(mat_dat.shape)
  while np.any(mat_dat > 9):
    list_9 = np.where(mat_dat > 9)
    for i in range(len(list_9[0])):
      x = list_9[0][i] 
      y = list_9[1][i] 
      flash(x,y)
  total = total + sum(sum(mat_dat == 0))

print(mat_dat)    
total

[[8 7 3 1 1 1 1 5 4 4]
 [7 2 3 5 1 1 8 5 4 4]
 [2 2 2 3 4 4 8 5 5 5]
 [2 2 2 2 2 2 2 7 7 1]
 [2 2 2 2 2 2 2 8 9 1]
 [2 2 2 2 2 2 2 3 4 8]
 [6 2 2 2 2 2 2 3 1 5]
 [4 5 6 6 6 6 6 6 5 4]
 [4 4 3 3 3 3 3 3 3 3]
 [0 4 3 3 3 3 3 3 3 3]]


1691

In [145]:
# part 2

data_int = []
n = data.shape[0]
for i in range(n):
  data_int.append([int(x) for x in str(data[0][i])])

mat_dat = np.array(data_int)
m = mat_dat.shape[1]

other_timestep = True
t = 0
while other_timestep:
  time_step()
  t = t + 1
  has_flashed = np.zeros(mat_dat.shape)
  while np.any(mat_dat > 9):
    list_9 = np.where(mat_dat > 9)
    for i in range(len(list_9[0])):
      x = list_9[0][i] 
      y = list_9[1][i] 
      flash(x,y)
  n_flashing = sum(sum(mat_dat == 0))
  if n_flashing == mat_dat.shape[0] * mat_dat.shape[1]:
    other_timestep = False
print(mat_dat)    
t


[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


216

100