In [116]:
import pandas as  pd
import numpy as np
data = pd.read_table('sample_data/input_5.txt',header = None)
n = 1000
m = data.shape[0]

In [105]:
# advent 5 part 1

ocean_floor = np.zeros((n,n))

for i in range(m):
  coords = data[0][i].split(' -> ')
  [x1,y1] = coords[0].split(',')
  [x2,y2] = coords[1].split(',')
  x1 = (int(x1))
  y1 = (int(y1))
  x2 = (int(x2))
  y2 = (int(y2))
  if x1 == x2:
    for j in np.arange(min(y1,y2),max(y1,y2) + 1):
      ocean_floor[x1][j] = ocean_floor[x1][j]+1
  if y1 == y2:
    for j in np.arange(min(x1,x2),max(x1,x2) + 1):
      ocean_floor[j][y1] = ocean_floor[j][y1]+1
print(ocean_floor)
sum(sum(ocean_floor > 1))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


6397

In [118]:
# advent 5 part 2

ocean_floor = np.zeros((n,n))

for i in range(m):
  coords = data[0][i].split(' -> ')
  [x1,y1] = coords[0].split(',')
  [x2,y2] = coords[1].split(',')
  x1 = (int(x1))
  y1 = (int(y1))
  x2 = (int(x2))
  y2 = (int(y2))
  if x1 == x2:
    for j in np.arange(min(y1,y2),max(y1,y2) + 1):
      ocean_floor[x1][j] = ocean_floor[x1][j]+1
  elif y1 == y2:
    for j in np.arange(min(x1,x2),max(x1,x2) + 1):
      ocean_floor[j][y1] = ocean_floor[j][y1]+1
  elif (max(x1,x2) - min (x1,x2) == max(y1,y2) - min (y1,y2)):
    if x1 > x2:
      x_range = np.arange(x1,y2-1,-1)
    else:
      x_range = np.arange(y1,y2+1)
    if y1 > y2:
      y_range = np.arange(y1,x2-1,-1)
    else: 
      y_range = np.arange(y1,y2+1)
    print(len(x_range) == len(y_range))
    #for j in range(len(x_range)):
      #ocean_floor[x_range[j]][y_range[j]]= ocean_floor[x_range[j]][y_range[j]] + 1 

sum(sum(ocean_floor > 1))

True
False
False
True
True
False
False
True
True
False
False
False
False
False
True
False
False
False
False
False
False
False
False
False
False
True
False
True
False
True
True
False
True
True
True
True
False
True
False
False
False
True
True
False
True
False
False
False
False
False
False
True
False
True
True
True
True
True
False
False
False
False
True
False
True
False
True
False
False
False
False
False
True
False
False
True
False
False
True
False
False
False
False
False
False
False
True
False
False
False
False
False
False
False
False
True
False
True
True
True
False
True
True
False
False
False
False
False
True
False
False
False
True
False
False
False
False
True
True
False
False
True
False
False
True
False
False
False
False
False
True
False
False
False
False
False
False
False
False
False
True
False
True
False
False
True
False
False
False
False
False
False
True
True
False
False
False
False
True
False
True
True


6397

In [92]:
data

0
0  0,9 -> 5,9
1  8,0 -> 0,8
2  9,4 -> 3,4
3  2,2 -> 2,1
4  7,0 -> 7,4
5  6,4 -> 2,0
6  0,9 -> 2,9
7  3,4 -> 1,4
8  0,0 -> 8,8
9  5,5 -> 8,2